### ISSUE TITLE
Look with Set Font Size add-on

### ISSUE THREAD

**Issue by omega3** [calumks/anki-more-overview-stats#8]
Thank you very much for Due tomorrow.

Would it be possible to correct the way it is displayed when "Set Font Size" add-on is used:
https://imgur.com/AWQgqfV

I set font size to 19.

Set Font Size
https://ankiweb.net/shared/info/651521808

**Comment by teaqu** [comment]
Looks fine on Windows 10. What OS are you using? Thanks!

**Comment by omega3** [comment]
Anki version 2.1.12 (eef86bf3)
Qt 5.12.1 PyQt 5.11.3

Operating System: Manjaro Linux 
KDE Plasma Version: 5.15.4
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.2
Kernel Version: 5.0.7-1-MANJARO
OS Type: 64-bit

Maybe it depends on screen resolution? My is not wide. It is 1280x1024.

Check bigger font, like 25 or more to see if this happens.

**Comment by teaqu** [comment]
Should be fixed with latest update.

![new_width](https://user-images.githubusercontent.com/583418/56898633-6d665e80-6a89-11e9-89bf-96bba97b444b.png)

**Comment by omega3** [comment]
My still doesn't look good:
https://imgur.com/aZHU55O

But I have more digits in one row: for Total cards there is 11 digits. Is the position of this fixed in center of Anki window?

I use Anki that is not installed but I run it from /bin/anki unpacked from ready self sufficient Linux package (tar.bz2) so it should be not affected by system theme. Also disabling Night mode doesn't affect this look.

**Comment by teaqu** [comment]
Alright try now. The table should now adapt to different sizes rather than a fixed width.

**Comment by omega3** [comment]
Now is correct.
https://imgur.com/u3eS0UX

It is fixed. Thank you very much.

**Comment by teaqu** [comment]
Nice :). Thank you for reporting!
